.PHONY: all setup generate_data migrate_data clean

# Default target
all: setup generate_data migrate_data

# Setup environment
setup-dir:
	data-migrate setup-dir

# Generate data
atlas-migrate:
	@echo "Not implemented"
	

# Generate Users
generate-users:
	@echo "Not implemented"

# Generate data templates
generate-data-templates:
	@echo "Not implemented"

# populate database
populate-db:
	@echo "Not implemented"